# Generated by Django 2.1 on 2024-07-25 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnoAcademico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anoacademico',
            name='Activo',
            field=models.BooleanField(default=False),
        ),
    ]
