# Generated by Django 2.1 on 2022-04-15 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notascomp',
            name='jeje',
            field=models.CharField(default='-', max_length=25),
        ),
    ]
