# Generated by Django 2.1 on 2022-04-15 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notas', '0002_notascomp_jeje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notascomp',
            name='jeje',
        ),
    ]
