# Generated by Django 2.1 on 2022-04-04 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Competencias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competencias',
            name='nivel',
            field=models.CharField(choices=[('PRIM', 'PRIM'), ('SEC', 'SEC')], default='PRIM', max_length=10),
        ),
    ]
