# Generated by Django 2.1 on 2024-04-01 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Competencias', '0002_competencias_nivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='competencias',
            name='Orden',
            field=models.IntegerField(default=1),
        ),
    ]
