# Generated by Django 2.1 on 2024-04-02 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Competencias', '0003_competencias_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='competencias',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
