# Generated by Django 2.1 on 2024-07-23 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Competencias', '0004_competencias_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competencias',
            name='status',
            field=models.BooleanField(choices=[(True, 'HABILITADO'), (False, 'INHABILITADO')], default=True),
        ),
    ]
