# Generated by Django 2.1 on 2024-07-27 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TempDatos', '0003_auto_20240727_1638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tempdatos',
            old_name='Docente',
            new_name='DocenteCurso',
        ),
    ]
