# Generated by Django 2.1 on 2024-07-23 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AnoAcademico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=60)),
                ('AnoAcademico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AnoAcademico.AnoAcademico', verbose_name='Año Académico')),
            ],
        ),
    ]
