# Generated by Django 2.1 on 2024-07-28 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Aulas', '0001_initial'),
        ('Docente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='Aula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Aulas.Aulas', verbose_name='Aulas'),
        ),
    ]
