# Generated by Django 2.1 on 2024-04-01 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Curso', '0002_auto_20240401_0018'),
        ('PeriodoAcademico', '0001_initial'),
        ('Docente', '0001_initial'),
        ('Competencias', '0003_competencias_orden'),
        ('Matricula', '0001_initial'),
        ('Notas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotasComp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nota', models.CharField(default='-', max_length=250)),
                ('Competencias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Competencias.Competencias')),
                ('Curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Curso.Curso')),
                ('Docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Docente.Docente')),
                ('Matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Matricula.Matricula')),
                ('PAcademico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PeriodoAcademico.PAcademico')),
            ],
        ),
    ]
