# Generated by Django 2.1 on 2024-07-26 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Aulas', '0001_initial'),
        ('Notas', '0002_notascomp'),
    ]

    operations = [
        migrations.AddField(
            model_name='notascomp',
            name='Aulas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Aulas.Aulas'),
        ),
    ]
