# Generated by Django 2.1 on 2024-07-26 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DocenteCurso', '0003_auto_20240726_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docentecurso',
            name='Aulas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aula_id', to='Aulas.Aulas', verbose_name='Aulas'),
        ),
        migrations.AlterField(
            model_name='docentecurso',
            name='Curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curso_id', to='Curso.Curso'),
        ),
        migrations.AlterField(
            model_name='docentecurso',
            name='Docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docente_id', to='Docente.Docente'),
        ),
    ]
