# Generated by Django 2.1 on 2024-07-24 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Nivel', '0001_initial'),
        ('Grado', '0001_initial'),
        ('AnoAcademico', '0001_initial'),
        ('Seccion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aulas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AnoAcademico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AnoAcademico.AnoAcademico', verbose_name='Año Academico')),
                ('Grado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Grado.Grado', verbose_name='Grado Académico')),
                ('Nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Nivel.Nivel', verbose_name='Nivel Académico')),
                ('Seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seccion.Seccion', verbose_name='Sección Académico')),
            ],
        ),
    ]
